# -------- Build stage --------
FROM node:20 AS build
WORKDIR /app
COPY ../frontend/package*.json ./
RUN npm install
COPY ../frontend ./
RUN npm run build

# -------- Runtime stage --------
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY /nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build .
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]